-- Схема для Supabase Nail Studio
create table if not exists services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  price integer not null default 0,
  duration_minutes integer not null default 60,
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists appointments (
  id bigint generated by default as identity primary key,
  client_name text not null,
  client_phone text not null,
  service_id bigint references services(id),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  comment text default '',
  status text not null default 'booked',
  created_at timestamptz not null default now()
);

create table if not exists blocked_time (
  id bigint generated by default as identity primary key,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reason text default ''
);

create table if not exists schedule_rules (
  id bigint generated by default as identity primary key,
  weekday integer not null check (weekday between 0 and 6),
  is_working boolean not null default true,
  start_time time,
  end_time time
);

create table if not exists promos (
  id bigint generated by default as identity primary key,
  title text not null,
  body text default '',
  image_url text,
  active boolean not null default false,
  starts_on date,
  ends_on date,
  created_at timestamptz not null default now()
);

create table if not exists gallery (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- Политики безопасности нужно включить после создания admin-пользователя.
-- Публичным клиентам будут доступны только чтение активных услуг/акций/галереи
-- и безопасное создание записи через функцию/Edge Function.
-- Изменение расписания, услуг и записей — только авторизованному администратору.
